name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install Bicep
      run: |
        wget https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x bicep-linux-x64
        sudo mv ./bicep-linux-x64 /usr/local/bin/bicep
    - name: Build and deploy
      run: |
        bicep build ./azuredeploy.bicep
        az deployment group create --resource-group SwedenCentralALZTest --template-file ./azuredeploy.json --parameters @./azuredeploy.parameters.json
